export const ga4Schema = {
    _em: 'em',
    event_name: 'en',
    protocol_version: 'v',
    _page_id: '_p',
    _is_debug: '_dbg',
    tracking_id: 'tid',
    hit_count: '_s',
    user_id: 'uid',
    client_id: 'cid',
    page_location: 'dl',
    language: 'ul',
    firebase_id: '_fid',
    traffic_type: 'tt',
    ignore_referrer: 'ir',
    screen_resolution: 'sr',
    global_developer_id_string: 'gdid',
    redact_device_info: '_rdi',
    geo_granularity: '_geo',
    _is_passthrough_cid: 'gtm_up',
    _is_linker_valid: '_glv',
    _user_agent_architecture: 'uaa',
    _user_agent_bitness: 'uab',
    _user_agent_full_version_list: 'uafvl',
    _user_agent_mobile: 'uamb',
    _user_agent_model: 'uam',
    _user_agent_platform: 'uap',
    _user_agent_platform_version: 'uapv',
    _user_agent_wait: 'uaW',
    _user_agent_wow64: 'uaw',
    error_code: 'ec',
    session_id: 'sid',
    session_number: 'sct',
    session_engaged: 'seg',
    page_referrer: 'dr',
    page_title: 'dt',
    currency: 'cu',
    campaign_content: 'cc',
    campaign_id: 'ci',
    campaign_medium: 'cm',
    campaign_name: 'cn',
    campaign_source: 'cs',
    campaign_term: 'ck',
    engagement_time_msec: '_et',
    event_developer_id_string: 'edid',
    is_first_visit: '_fv',
    is_new_to_site: '_nsi',
    is_session_start: '_ss',
    is_conversion: '_c',
    euid_mode_enabled: 'ecid',
    non_personalized_ads: '_npa',
    create_google_join: 'gaz',
    is_consent_update: 'gsu',
    user_ip_address: 'uip',
    google_consent_state: 'gcs',
    google_consent_update: 'gcu',
    us_privacy_string: 'uip',
    document_location: 'dl',
    document_path: 'dp',
    document_title: 'dt',
    document_referrer: 'dr',
    user_language: 'ul',
    document_hostname: 'dh',
    item_id: 'id',
    item_name: 'nm',
    item_brand: 'br',
    item_category: 'ca',
    item_category2: 'c2',
    item_category3: 'c3',
    item_category4: 'c4',
    item_category5: 'c5',
    item_variant: 'va',
    price: 'pr',
    quantity: 'qt',
    coupon: 'cp',
    item_list_name: 'ln',
    index: 'lp',
    item_list_id: 'li',
    discount: 'ds',
    affiliation: 'af',
    promotion_id: 'pi',
    promotion_name: 'pn',
    creative_name: 'cn',
    creative_slot: 'cs',
    location_id: 'lo',
    // legacy ecommerce
    id: 'id',
    name: 'nm',
    brand: 'br',
    variant: 'va',
    list_name: 'ln',
    list_position: 'lp',
    list: 'ln',
    position: 'lp',
    creative: 'cn',
}

export const ecommerceEvents = [
    'add_payment_info',
    'add_shipping_info',
    'add_to_cart',
    'remove_from_cart',
    'view_cart',
    'begin_checkout',
    'select_item',
    'view_item_list',
    'select_promotion',
    'view_promotion',
    'purchase',
    'refund',
    'view_item',
    'add_to_wishlist',
]
